name: 🚬

on:
  push:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
          node-version: "12"
      - run: yarn build
      - uses: ./
        with:
          file: examples/smoke.yaml
